language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - echo "extension=ldap.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

before_script:
  - composer selfupdate
  - composer install
script: phpunit -c app/phpunit.xml.dist
