imports:
    - { resource: parameters.yml }
    - { resource: myparameters.yml }
    - { resource: security.yml }

framework:
    session:
        name: "oic-p"
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/bin/node
            node_paths: [/usr/lib/node_modules]
            apply_to: "\.less$"
        cssembed: 
            jar: %kernel.root_dir%/../vendor/scribe/cssembed-library/dist/cssembed.jar
        yui_css:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        cssrewrite: ~
    assets:
        bootstrap_css:
            inputs:
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - less
                - cssrewrite
        other_less:
            inputs:
                - @WaldoOpenIdConnectProviderBundle/Resources/less/provider.less
                - @WaldoOpenIdConnectEnduserBundle/Resources/less/enduser.less
            filters:
                - less
                - cssrewrite
        other_css:
            inputs: ~
        admin_css:
            inputs:
                - @WaldoOpenIdConnectAdminBundle/Resources/less/admin.less
                - %kernel.root_dir%/../vendor/almasaeed2010/AdminLTE/css/AdminLTE.css
                - %kernel.root_dir%/../vendor/DataTables/Plugins/integration/bootstrap/3/dataTables.bootstrap.css
                
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
#                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
#                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            output: js/bootstrap.js
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
        other_js:
            inputs: ~                
        admin_js:
            inputs:
                - %kernel.root_dir%/../vendor/almasaeed2010/AdminLTE/js/AdminLTE/app.js
                - %kernel.root_dir%/Resources/public/datatable/js/jquery.dataTables.js
                - %kernel.root_dir%/../vendor/DataTables/Plugins/integration/bootstrap/3/dataTables.bootstrap.js
                - @WaldoOpenIdConnectAdminBundle/Resources/js/templating.js

braincrafted_bootstrap:
    less_filter: less
    fonts_dir: %kernel.root_dir%/../web/fonts

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

ali_datatable:  
    all: 
        action:           false
        search:           true
    js:
        aLengthMenu: "[[5, 10, 25, 50], [5, 10, 25, 50]]"
        bJQueryUI:  false

waldo_oic_p:
    base_url: "%issuer%"
    issuer: "%issuer%"
    private_key: "%kernel.root_dir%/Resources/key/private_key"
