security:
    encoders:
        Waldo\OpenIdConnect\ProviderBundle\Entity\Account: 
            algorithm: bcrypt
            cost: 12
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        accounts:
            entity: { class: WaldoOpenIdConnectProviderBundle:Account, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        authenticationArea:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                
    access_control:
        - { path: ^/authentication/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/authorize, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/authentication/, roles: ROLE_USER }
