security:
    encoders:
        Waldo\OpenIdConnect\ProviderBundle\Entity\Account: 
            algorithm: bcrypt
            cost: 12
        
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
