security:
    encoders:
        Waldo\OpenIdConnect\ModelBundle\Entity\Account: 
            algorithm: bcrypt
            cost: 12
        Waldo\OpenIdConnect\ModelBundle\Entity\Client: plaintext
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        accounts:
            entity: { class: WaldoOpenIdConnectModelBundle:Account, property: username }
        clients:
            entity: { class: WaldoOpenIdConnectModelBundle:Client, property: clientId }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        tokenArea:
            pattern:   ^/token
            anonymous: ~
            provider: clients
            http_basic:
                realm: "Secured Area"

        authenticationArea:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                success_handler: waldo_oic_p.success_handler.auth
                csrf_provider: form.csrf_provider
            logout:
                path: logout
                success_handler: waldo_oic_p.success_handler.logout
            switch_user: ~
                
    access_control:
        - { path: ^/token, roles: ROLE_OIC_CLIENT }
        - { path: ^/authentication/login(/)?(.*)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/authorize, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/authentication/, roles: ROLE_USER }
        - { path: ^/account/, roles: ROLE_USER }
        - { path: ^/admin/, roles: ROLE_ADMIN }
